AVX-26997 update terraform aviatrix OCI module source url and output …
AviatrixSystems/terraform-module-oci pull request #10
Opened 2022-08-05 20:07 UTC by MingweiZhu666

…description

2022-08-05 22:00 UTC, inc1t3Ful requested changes
Please update the READMEs in the submodules as well, to match the format of the main README

2022-08-05 22:00 UTC, inc1t3Ful commented on example/README.md
> +  source           = "github.com/AviatrixSystems/terraform-module-oci.git//modules/aviatrix-controller-build"
these source links are actually incorrect. You should now be sourcing from the registry

2022-08-05 22:00 UTC, inc1t3Ful commented on example/README.md
> +  source                        = "github.com/AviatrixSystems/terraform-module-oci.git//modules/aviatrix-controller-initialize"
See above, need to source from registry instead of github

2022-08-05 22:20 UTC, MingweiZhu666 commented on example/README.md
> +  source           = "github.com/AviatrixSystems/terraform-module-oci.git//modules/aviatrix-controller-build"
yes, I just find it, fix now. thank you

2022-08-05 22:41 UTC, MingweiZhu666 commented
> Please update the READMEs in the submodules as well, to match the format of the main README

have fixed

2022-08-06 00:06 UTC, inc1t3Ful approved these changes
One more reminder to double check your examples, in case you still have sensitive data leftover, before merging

2022-08-06 00:06 UTC, inc1t3Ful commented on modules/aviatrix-controller-initialize/README.md
> +|     aviatrix_customer_id      |             Aviatrix customer license id".             |
remove the random trailing " quotation

2022-08-06 00:07 UTC, inc1t3Ful requested changes
see above- accidentally hit approve

2022-08-08 16:47 UTC, MingweiZhu666 commented
> One more reminder to double check your examples, in case you still have sensitive data leftover, before merging

have checked and fixed, thank you

2022-08-09 02:57 UTC, inc1t3Ful approved these changes

2022-08-12 19:55 UTC, zhiqiangjin approved these changes

2022-08-12 19:55 UTC, merged